monolog:
    channels:
        - deprecation # Les dépréciations sont enregistrées dans le canal "deprecation" dédié

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            deprecation:
                type: stream
                path: "%kernel.logs_dir%/deprecations.log" # Enregistre les dépréciations dans un fichier séparé
                level: warning # Changez le niveau de log pour les dépréciations

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            deprecation:
                type: stream
                path: "%kernel.logs_dir%/deprecations.log"
                level: warning # Changez le niveau de log pour les dépréciations

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                path: php://stderr
                level: error # Changez le niveau de log pour éviter de voir trop de messages debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: "%kernel.logs_dir%/deprecations.log" # Enregistre les dépréciations dans un fichier séparé
                level: warning # Changez le niveau de log pour les dépréciations
                formatter: monolog.formatter.json