# config/services.yaml
services:
    # configuration par défaut pour les services de ce fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services
        autoconfigure: true # Enregistre automatiquement vos services comme commandes, abonnés aux événements, etc.

    # rend les classes de src/ disponibles comme services
    # crée un service par classe dont l'id est le nom de classe complètement qualifié
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Enregistrement explicite du AccessVoter pour s'assurer qu'il est bien reconnu comme un voter
    App\Security\AccessVoter:
        tags: ['security.voter']
